CREATE OR REPLACE TABLE access_logs AS
SELECT *
FROM read_csv(
        '*.gz',
        delim = '\t',
        nullstr = '-',
        header = false,
        auto_detect = false,
        skip = 2,
        COLUMNS = {
            'date': 'DATE',
            'time': 'time',
            'x_edge_location': 'VARCHAR',
            'sc_bytes': 'BIGINT',
            'c_ip': 'VARCHAR',
            'cs_method': 'VARCHAR',
            'cs_host': 'VARCHAR',
            'cs_uri_stem': 'VARCHAR',
            'sc_status': 'INT',
            'cs_referer': 'VARCHAR',
            'cs_user_agent': 'VARCHAR',
            'cs_uri_query': 'VARCHAR',
            'cs_cookie': 'VARCHAR',
            'x_edge_result_type': 'VARCHAR',
            'x_edge_request_id': 'VARCHAR',
            'x_host_header': 'VARCHAR',
            'cs_protocol': 'VARCHAR',
            'cs_bytes': 'BIGINT',
            'time_taken': 'DOUBLE',
            'x_forwarded_for': 'VARCHAR',
            'ssl_protocol': 'VARCHAR',
            'ssl_cipher': 'VARCHAR',
            'x_edge_response_result_type': 'VARCHAR',
            'cs_protocol_version': 'VARCHAR',
            'fle_status': 'VARCHAR',
            'fle_encrypted_fields': 'VARCHAR',
            'c_port': 'INT',
            'time_to_first_byte': 'DOUBLE',
            'x_edge_detailed_result_type': 'VARCHAR',
            'sc_content_type': 'VARCHAR',
            'sc_content_len': 'BIGINT',
            'sc_range_start': 'BIGINT',
            'sc_range_end': 'BIGINT'
        }
    );